/*
 * The guest toolkit, from the source of truth.
 *
 *   node scripts-toolkit.mjs > src/toolkit.h
 *
 * `toText`, `slug`, `visit` and `h` are the four names a document's own code
 * can use, and mdy-docs defines them as GUEST SOURCE — spliced into every
 * program rather than bound as host functions, because two of them take a
 * callback and a callback cannot cross the boundary. So the C engine splices
 * the same source, and takes it from mdy.js rather than keeping a copy that
 * can drift.
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const source = readFileSync(join(here, '..', '..', 'src', 'mdy.js'), 'utf8');
const match = /^const TOOLKIT = `\n([\s\S]*?)^`;$/m.exec(source);
if (!match) {
  console.error('scripts-toolkit: could not find TOOLKIT in src/mdy.js');
  process.exit(1);
}

/* It is a template literal in mdy.js, so its own escapes are for JavaScript's
 * lexer and have to come off before it is a C string. */
const toolkit = match[1].replace(/\\\\/g, '\\').replace(/\\`/g, '`').replace(/\\\$/g, '$');

const cLines = toolkit.split('\n').map(
  (line) => '    "' + line.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '\\n"'
);

process.stdout.write(`/* Generated by scripts-toolkit.mjs from ../../src/mdy.js — do not edit.
 *
 * The four names a document's code can use. mdy-docs splices them into every
 * program as guest source rather than binding them as host functions, because
 * visit and transform take callbacks and a callback cannot cross the
 * boundary. The C engine splices the same source.
 */
#ifndef MDY_TOOLKIT_H
#define MDY_TOOLKIT_H

static const char MDY_TOOLKIT[] =
${cLines.join('\n')};

#endif
`);
